apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: online-boutique
  namespace: onlineboutique
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: online-boutique
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50